### ISSUE TITLE
Portfolio Site Refresh

### ISSUE THREAD

**Issue by singularityhacker** [singularityhacker/Justice-Conder-2021#1]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24150%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/singularityhacker/Justice-Conder-2021/issues/1)

Background

My current site is kludgy and slow. Before updating and adding updates from the past two years, I thought it would be a good idea to deal with the performance issues first. I started to recreate the site using Bulma but am not the front-end dev I used to be and am too busy with work to spend the time it would take me. 

Request

Please make the necessary updates to the 2021 personal site revision to make it look like my existing site. I’m looking for the basic grid system, section blocks, color scheme, and fonts. Don’t worry about implementing that giant map footer in the existing version. You can leave the footer present in the new Bulma version. It’s surely more performant anyway. Even changes that can be made to ensure the new site is as fast and snappy as possible would be greatly appreciated. 

Existing site (old/existing)

*   Live: https://www.justiceconder.com/
*   Repo: https://github.com/singularityhacker/Justice-Conder
*   Google page speed test is [terrible](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.justiceconder.com%2F&tab=mobile)

2021 Revision Starter (new / fresh start):

*   Live: https://peaceful-newton-7a6de3.netlify.app/
*   Repo: https://github.com/singularityhacker/Justice-Conder-2021

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $150.00)

- [<img src='https://avatars1.githubusercontent.com/u/1808235?v=4' alt='singularityhacker' width=24 height=24> singularityhacker](https://issuehunt.io/u/singularityhacker) ($150.00)

### Submitted pull Requests
- [#2 Update and improved performance of the site](https://issuehunt.io/r/singularityhacker/Justice-Conder-2021/pull/2)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/singularityhacker/Justice-Conder-2021/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by oOBoomberOo** [comment]
I want to work on this. I assume no one has been assigned to this yet?

**Comment by singularityhacker** [comment]
@oOBoomberOo That would be correct! It's all yous! :) Thanks for responding :mechanical\_arm:

**Comment by singularityhacker** [comment]
@oOBoomberOo Any updates?

**Comment by oOBoomberOo** [comment]
Sure @singularityhacker !
I've replicated the site layout so I would say I'm about 90% finish now.  
I still need to handle responsiveness on a mobile device though.

You can see the site here: https://eloquent-colden-c5ed1d.netlify.app/

And this is the lighthouse score currently, in case you were wondering:
![image](https://user-images.githubusercontent.com/26600816/105606828-da359680-5dde-11eb-8b20-c13f04f3408f.png)

**Comment by singularityhacker** [comment]
@oOBoomberOo This is just spectacular:ok\_hand:  You're the frigin bomb, boomer! Wow. This is what I was looking for. Would you like a "built by" link in the footer linking to your Github profile when it's all said and done or is that too extra?

**Comment by oOBoomberOo** [comment]
If you are fine with it, I would be glad to have my profile link in the footer.

**Comment by oOBoomberOo** [comment]
I've finished updating the website now @singularityhacker

**Comment by singularityhacker** [comment]
You are a dream!! Wow, I could not be more pleased. I will be added your profile link in the footer. Fantastic work! :ok\_hand:
